# Copyright 2026 Google LLC
# Licensed under the Apache License, Version 2.0

"""
agent_runtime_app.py — Production wrapper for Agent Runtime deployment.

This module is generated by `agents-cli scaffold enhance --deployment-target agent_runtime`.
It exposes the ADK App via a FastAPI server compatible with Agent Runtime's
REST API contract (:query endpoint).
"""

from __future__ import annotations

import os

import uvicorn
from google.adk.cli.fast_api import get_fast_api_app

from app.agent import app as adk_app

# Agent Runtime reads PORT from environment; default to 8080 for Cloud Run
PORT = int(os.environ.get("PORT", 8080))

fast_api_app = get_fast_api_app(
    agent_dir=".",
    session_db_url="agentengine://",   # Managed session store on Agent Runtime
    allow_origins=["*"],
)

if __name__ == "__main__":
    uvicorn.run(fast_api_app, host="0.0.0.0", port=PORT)
